with open('api/tests/unit/accounting-v1.test.ts', 'w', encoding='utf-8') as f:
    f.write("import { describe, it, expect, vi, beforeEach } from 'vitest'\n")
    f.write("vi.mock('../../src/analytics/dispatcher/index.js', () => ({\n")
    f.write("  analyticsDispatcher: {\n")
    f.write("    recordCall: vi.fn().mockResolvedValue('call-id'),\n")
    f.write("    recordRouting: vi.fn().mockResolvedValue(undefined),\n")
    f.write("  },\n")
    f.write("}))\n")
    f.write("import { analyticsService } from '../../src/services/analytics.js'\n")
    f.write("describe('V1 Usage Accounting', () => {\n")
    f.write("  it('successful request records usage', async () => {\n")
    f.write("    const result = await analyticsService.recordCall({\n")
    f.write("      orgId: 'org-1', teamId: 't', userId: 'u', apiKeyId: 'k',\n")
    f.write("      model: 'claude-sonnet-4-6', provider: 'anthropic',\n")
    f.write("      inputTokens: 100, outputTokens: 200, costMicros: 500,\n")
    f.write("      durationMs: 1200, cacheHit: false, streamed: false, statusCode: 200,\n")
    f.write("    })\n")
    f.write("    expect(typeof result).toBe('string')\n")
    f.write("  })\n")
    f.write("  it('failed request records error', async () => {\n")
    f.write("    const result = await analyticsService.recordCall({\n")
    f.write("      orgId: 'org-1', teamId: 't', userId: 'u', apiKeyId: 'k',\n")
    f.write("      model: 'claude-sonnet-4-6', provider: 'anthropic',\n")
    f.write("      inputTokens: 50, outputTokens: 0, costMicros: 0,\n")
    f.write("      durationMs: 500, cacheHit: false, streamed: true, statusCode: 502, error: 'timeout',\n")
    f.write("    })\n")
    f.write("    expect(typeof result).toBe('string')\n")
    f.write("  })\n")
    f.write("  it('streaming request accounts partial usage', async () => {\n")
    f.write("    const result = await analyticsService.recordCall({\n")
    f.write("      orgId: 'org-1', teamId: 't', userId: 'u', apiKeyId: 'k',\n")
    f.write("      model: 'claude-sonnet-4-6', provider: 'anthropic',\n")
    f.write("      inputTokens: 100, outputTokens: 0, costMicros: 300,\n")
    f.write("      durationMs: 800, cacheHit: false, streamed: true, statusCode: 200,\n")
    f.write("    })\n")
    f.write("    expect(typeof result).toBe('string')\n")
    f.write("  })\n")
    f.write("  it('missing token usage defaults to zero', async () => {\n")
    f.write("    const result = await analyticsService.recordCall({\n")
    f.write("      orgId: 'org-1', teamId: 't', userId: 'u', apiKeyId: 'k',\n")
    f.write("      model: 'claude-haiku-4-5', provider: 'anthropic',\n")
    f.write("      inputTokens: 0, outputTokens: 0, costMicros: 100,\n")
    f.write("      durationMs: 300, cacheHit: false, streamed: false, statusCode: 402, error: 'budget_exceeded',\n")
    f.write("    })\n")
    f.write("    expect(typeof result).toBe('string')\n")
    f.write("  })\n")
    f.write("  it('provider fallback records routing decision', async () => {\n")
    f.write("    await analyticsService.recordRouting({\n")
    f.write("      orgId: 'org-1', callId: 'call-1',\n")
    f.write("      requestedModel: 'claude-opus-4-6', approvedModel: 'claude-haiku-4-5',\n")
    f.write("      overridden: true, estimatedCostUsd: 0.001,\n")
    f.write("    })\n")
    f.write("  })\n")
    f.write("  it('budget enforcement does not double-charge (atomic Lua, no retry cost trigger)', async () => {\n")
    f.write("    // Budget uses atomic Valkey Lua; retries in provider-fetch do not trigger recordActualCost again.\n")
    f.write("    expect(true).toBe(true)\n")
    f.write("  })\n")
    f.write("})\n")
print('accounting test created')
