with open('docs/CURL.md', 'w', encoding='utf-8') as f:
    f.write('# TokenSentry - Curl Examples for Debugging\n\n')
    f.write('## Basic request\n')
    f.write("curl -X POST https://api.tokensentry.ai/v1/proxy \\\n")
    f.write("  -H \"Authorization: Bearer ts_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxx\" \\\n")
    f.write("  -H \"Content-Type: application/json\" \\\n")
    f.write("  -d '{\"model\":\"claude-sonnet-4-6\",\"messages\":[{\"role\":\"user\",\"content\":\"Hello\"}]}'}\n\n")
    f.write('## Streaming request\n')
    f.write("curl -X POST https://api.tokensentry.ai/v1/proxy \\\n")
    f.write("  -H \"Authorization: Bearer ts_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxx\" \\\n")
    f.write("  -H \"Content-Type: application/json\" \\\n")
    f.write("  -d '{\"model\":\"claude-sonnet-4-6\",\"messages\":[{\"role\":\"user\",\"content\":\"Hello\"}],\"stream\":true}'\n\n")
    f.write('## Health checks\n')
    f.write('curl https://api.tokensentry.ai/health/live\n')
    f.write('curl https://api.tokensentry.ai/health/ready\n')
print('CURL.md written')
