content = open('api/src/analytics/dispatcher/postgres-dispatcher.ts', 'r', encoding='utf-8').read()
content = content.replace('        callId,', '        callId: callId || `unknown-${Date.now()}`,')
content = content.replace('        inputTokens: params.inputTokens,', '        inputTokens: Math.max(0, params.inputTokens ?? 0),')
content = content.replace('        outputTokens: params.outputTokens,', '        outputTokens: Math.max(0, params.outputTokens ?? 0),')
content = content.replace('        costMicros: params.costMicros,', '        costMicros: Math.max(0, params.costMicros ?? 0),')
content = content.replace('        durationMs: params.durationMs,', '        durationMs: Math.max(0, params.durationMs ?? 0),')
content = content.replace('        cacheHit: params.cacheHit,', '        cacheHit: !!params.cacheHit,')
content = content.replace('        streamed: params.streamed,', '        streamed: !!params.streamed,')
content = content.replace('        statusCode: params.statusCode,', '        statusCode: params.statusCode ?? 200,')
open('api/src/analytics/dispatcher/postgres-dispatcher.ts', 'w', encoding='utf-8').write(content)
print('dispatcher resilient')
