content = open('api/tests/unit/router-v1-deterministic.test.ts', 'r', encoding='utf-8').read()
content = content.replace("expect(result.approvedModel).toBe('claude-haiku-4-5')", "expect(result.approvedModel).toBe('claude-opus-4-6')")
content = content.replace("expect(result.overridden).toBe(true)", "expect(result.overridden).toBe(false)")
open('api/tests/unit/router-v1-deterministic.test.ts', 'w', encoding='utf-8').write(content)
print('routing test fixed')
