with open('api/tests/unit/agent-guard-v1.test.ts', 'w', encoding='utf-8') as f:
    f.write("import { describe, it, expect, vi, beforeEach } from 'vitest'\n")
    f.write("vi.mock('../../src/clients/valkey.js', () => ({\n")
    f.write("  valkey: {\n")
    f.write("    eval: vi.fn().mockResolvedValue([[{ agent_id: 'agent-1', org_id: 'org-1', status: 'active', started_at: '1234567890000', last_request_at: '1234568000000' }, { request_count: '5', tool_count: '0', input_tokens: '100', output_tokens: '200', retry_count: '0', provider_switch_count: '0', recursive_depth: '0', consecutive_errors: '0', last_provider: 'anthropic' }]]),\n")
    f.write("    multi: vi.fn().mockReturnValue({\n")
    f.write("      incr: vi.fn().mockReturnThis(),\n")
    f.write("      pttl: vi.fn().mockReturnThis(),\n")
    f.write("      exec: vi.fn().mockResolvedValue([[1], [-1]]),\n")
    f.write("    }),\n")
    f.write("    get: vi.fn(),\n")
    f.write("    setex: vi.fn(),\n")
    f.write("    hgetall: vi.fn().mockResolvedValue({ agent_id: 'agent-1', org_id: 'org-1', status: 'active', started_at: '1234567890000', last_request_at: '1234568000000', request_count: '5', tool_count: '0', input_tokens: '100', output_tokens: '200', retry_count: '0', provider_switch_count: '0', recursive_depth: '0', consecutive_errors: '0', last_provider: 'anthropic' }),\n")
    f.write("    hget: vi.fn(),\n")
    f.write("    hincrby: vi.fn(),\n")
    f.write("    hset: vi.fn(),\n")
    f.write("    zcard: vi.fn().mockResolvedValue(3),\n")
    f.write("    zremrangebyscore: vi.fn(),\n")
    f.write("    zrangebyscore: vi.fn().mockResolvedValue(['100', '200', '300']),\n")
    f.write("    del: vi.fn(),\n")
    f.write("    exists: vi.fn(),\n")
    f.write("    scan: vi.fn().mockResolvedValue(['0', []]),\n")
    f.write("  },\n")
    f.write("  ValkeyKeys: {\n")
    f.write("    agentSession: (sid: string) => `agent:session:${sid}`,\n")
    f.write("    agentStats: (sid: string) => `agent:stats:${sid}`,\n")
    f.write("    agentTimeline: (sid: string) => `agent:timeline:${sid}`,\n")
    f.write("    agentTools: (sid: string) => `agent:tools:${sid}`,\n")
    f.write("    agentProviders: (sid: string) => `agent:providers:${sid}`,\n")
    f.write("    agentTokenHistory: (sid: string) => `agent:token:${sid}`,\n")
    f.write("    agentBlocked: (sid: string) => `agent:blocked:${sid}`,\n")
    f.write("  },\n")
    f.write("  checkValkeyHealth: vi.fn().mockResolvedValue(true),\n")
    f.write("  closeValkey: vi.fn(),\n")
    f.write("}))\n")
    f.write("import { agentGuardService } from '../../src/services/agent-guard.js'\n")
    f.write("describe('Agent Guard V1', () => {\n")
    f.write("  beforeEach(() => { vi.clearAllMocks() })\n")
    f.write("  it('normal agent: allow', async () => {\n")
    f.write("    const result = await agentGuardService.evaluate({\n")
    f.write("      sessionId: 'sess-1', agentId: 'agent-1', orgId: 'org-1',\n")
    f.write("      inputTokens: 100, outputTokens: 200, toolCount: 0,\n")
    f.write("      provider: 'anthropic', budgetUtilization: 0.1, timestamp: Date.now(),\n")
    f.write("    }, [{ role: 'user', content: 'Hello' }])\n")
    f.write("    expect(result.action).toBe('allow')\n")
    f.write("    expect(result.blocked).toBe(false)\n")
    f.write("  })\n")
    f.write("  it('high-frequency agent: warn or block', async () => {\n")
    f.write("    const valkey = await import('../../src/clients/valkey.js')\n")
    f.write("    vi.mocked(valkey.valkey.zcard).mockResolvedValueOnce(15)\n")
    f.write("    const result = await agentGuardService.evaluate({\n")
    f.write("      sessionId: 'sess-high', agentId: 'agent-1', orgId: 'org-1',\n")
    f.write("      inputTokens: 100, outputTokens: 100, toolCount: 0,\n")
    f.write("      provider: 'anthropic', budgetUtilization: 0.1, timestamp: Date.now(),\n")
    f.write("    }, [{ role: 'user', content: 'Hello' }])\n")
    f.write("    expect(typeof result.score).toBe('number')\n")
    f.write("    expect(['allow', 'warn', 'block']).toContain(result.action)\n")
    f.write("  })\n")
    f.write("  it('retry storm: score reflects retries', async () => {\n")
    f.write("    const valkey = await import('../../src/clients/valkey.js')\n")
    f.write("    vi.mocked(valkey.valkey.hgetall).mockResolvedValueOnce({\n")
    f.write("      agent_id: 'agent-1', org_id: 'org-1', status: 'active', started_at: '123',\n")
    f.write("      request_count: '10', tool_count: '0', input_tokens: '500', output_tokens: '500',\n")
    f.write("      retry_count: '8', provider_switch_count: '0', recursive_depth: '0',\n")
    f.write("      consecutive_errors: '0', last_provider: 'anthropic',\n")
    f.write("    })\n")
    f.write("    const result = await agentGuardService.evaluate({\n")
    f.write("      sessionId: 'sess-retry', agentId: 'agent-1', orgId: 'org-1',\n")
    f.write("      inputTokens: 100, outputTokens: 100, toolCount: 0,\n")
    f.write("      provider: 'anthropic', budgetUtilization: 0.1, timestamp: Date.now(),\n")
    f.write("    }, [{ role: 'user', content: 'Hello' }, { role: 'user', content: 'Hello' }])\n")
    f.write("    expect(typeof result.score).toBe('number')\n")
    f.write("  })\n")
    f.write("  it('provider thrashing: score reflects switches', async () => {\n")
    f.write("    const valkey = await import('../../src/clients/valkey.js')\n")
    f.write("    vi.mocked(valkey.valkey.hgetall).mockResolvedValueOnce({\n")
    f.write("      agent_id: 'agent-1', org_id: 'org-1', status: 'active', started_at: '123',\n")
    f.write("      request_count: '5', tool_count: '0', input_tokens: '500', output_tokens: '500',\n")
    f.write("      retry_count: '0', provider_switch_count: '3', recursive_depth: '0',\n")
    f.write("      consecutive_errors: '0', last_provider: 'openai',\n")
    f.write("    })\n")
    f.write("    const result = await agentGuardService.evaluate({\n")
    f.write("      sessionId: 'sess-thrash', agentId: 'agent-1', orgId: 'org-1',\n")
    f.write("      inputTokens: 100, outputTokens: 100, toolCount: 0,\n")
    f.write("      provider: 'anthropic', budgetUtilization: 0.1, timestamp: Date.now(),\n")
    f.write("    }, [{ role: 'user', content: 'Hello' }])\n")
    f.write("    expect(typeof result.score).toBe('number')\n")
    f.write("    expect(result.factors.some(f => f.name === 'provider_thrashing')).toBe(true)\n")
    f.write("  })\n")
    f.write("  it('budget exhaustion: score increases with utilization', async () => {\n")
    f.write("    const result = await agentGuardService.evaluate({\n")
    f.write("      sessionId: 'sess-budget', agentId: 'agent-1', orgId: 'org-1',\n")
    f.write("      inputTokens: 100, outputTokens: 100, toolCount: 0,\n")
    f.write("      provider: 'anthropic', budgetUtilization: 0.95, timestamp: Date.now(),\n")
    f.write("    }, [{ role: 'user', content: 'Hello' }])\n")
    f.write("    const budgetFactor = result.factors.find(f => f.name === 'budget_exhaustion')\n")
    f.write("    expect(budgetFactor).toBeDefined()\n")
    f.write("    expect(budgetFactor!.score).toBeGreaterThanOrEqual(5)\n")
    f.write("  })\n")
    f.write("  it('blocked session: returns blocked result', async () => {\n")
    f.write("    const valkey = await import('../../src/clients/valkey.js')\n")
    f.write("    vi.mocked(valkey.valkey.get).mockResolvedValue('1')\n")
    f.write("    const blocked = await agentGuardService.isBlocked('sess-block')\n")
    f.write("    expect(blocked).toBe(true)\n")
    f.write("  })\n")
    f.write("  it('state expiration: session removed after TTL', async () => {\n")
    f.write("    await agentGuardService.removeSession('sess-expire')\n")
    f.write("    const session = await agentGuardService.getSession('sess-expire')\n")
    f.write("    expect(session).toBeNull()\n")
    f.write("  })\n")
    f.write("})\n")
print('agent-guard-v1 test written')
